feeds:
  - name: "NHKニュース"
    url: "https://www.nhk.or.jp/rss/news/cat0.xml"
  - name: "朝日新聞デジタル"
    url: "https://www.asahi.com/rss/asahi/newsheadlines.rdf"
  - name: "日経新聞"
    url: "https://assets.wor.jp/rss/rdf/nikkei/news.rdf"
  - name: "北日本新聞webunプラス - 全国ニュース"
    url: "https://webun.jp/list/feed/rss4news"
  - name: "熊本日日新聞"
    url: "https://kumanichi.com/rss.xml"
  - name: "はてブ新着 - 学び"
    url: "https://b.hatena.ne.jp/entrylist/knowledge.rss"
  - name: "はてブ新着 - おもしろ"
    url: "https://b.hatena.ne.jp/entrylist/fun.rss"
  - name: "はてブ新着 - エンタメ"
    url: "https://b.hatena.ne.jp/entrylist/entertainment.rss"
  - name: "はてブ新着 - 暮らし"
    url: "https://b.hatena.ne.jp/entrylist/life.rss"
  - name: "はてブ新着 - 政治と経済"
    url: "https://b.hatena.ne.jp/entrylist/economics.rss"
  - name: "はてブ新着 - 世の中"
    url: "https://b.hatena.ne.jp/entrylist/social.rss"
  - name: "はてブ新着 - 総合"
    url: "https://b.hatena.ne.jp/entrylist/general.rss"
  - name: "はてブ人気 - 学び"
    url: "https://b.hatena.ne.jp/hotentry/knowledge.rss"
  - name: "はてブ人気 - おもしろ"
    url: "https://b.hatena.ne.jp/hotentry/fun.rss"
  - name: "はてブ人気 - エンタメ"
    url: "https://b.hatena.ne.jp/hotentry/entertainment.rss"
  - name: "はてブ人気 - 暮らし"
    url: "https://b.hatena.ne.jp/hotentry/life.rss"
  - name: "はてブ人気 - 政治と経済"
    url: "https://b.hatena.ne.jp/hotentry/economics.rss"
  - name: "はてブ人気 - 世の中"
    url: "https://b.hatena.ne.jp/hotentry/social.rss"
  - name: "はてブ人気 - 総合"
    url: "https://b.hatena.ne.jp/hotentry/general.rss"
